// FIX: This file was corrupted. It has been cleaned and all necessary constants have been added and exported.
import { Sloka, Language, I18nContent, Testimonial, DarshanTier, DonationOption, Chant, ChakraTheme, Achievement, ChakraName, Badge } from './types';

// In a real app, these would be in separate files like 'i18n/en.ts'
const I18N_EN: I18nContent = {
    navHome: "Home",
    navTemples: "Temples",
    navDarshan: "Darshan",
    navPoojaServices: "Pooja Services",
    navYatras: "Yatras",
    navKnowledge: "Knowledge",
    navEvents: "Events",
    navDashboard: "Dashboard",
    navSeva: "Seva (Donate)",
    navMart: "Dharma Mart",
    navSettings: "Settings",
    bookingHistory: "Booking History",
    noBookings: "You have no bookings yet.",
    heroTitle: "Dharma Setu",
    heroSubtitle: "Your digital gateway to ancient temples, sacred knowledge, and spiritual experiences.",
    heroSearchPlaceholder: "Search for temples, books...",
    noResultsFound: "No Results Found",
    noResultsForQuery: "No results for '{query}'",
    searchResult: "Search Result",
    searchResults: "Search Results",
    searchResultsFor: "Search Results for",
    templesFound: "Temples Found",
    knowledgeFound: "Knowledge Found",
    eventsFound: "Events Found",
    dailySloka: "Verse of the Day",
    translation: "Translation",
    meaning: "Meaning",
    listen: "Listen",
    featuredTemples: "Featured Temples",
    readMore: "Read More",
    explorePoojas: "Explore Poojas",
    addPooja: "Add Pooja",
    addNewPooja: "Add New Pooja",
    editPooja: "Edit Pooja",
    addYatra: "Add Yatra",
    editYatra: "Edit Yatra",
    bookNow: "Book Now",
    bookDarshan: "Book Darshan",
    bookPooja: "Book Pooja",
    bookYatra: "Book Yatra",
    poojaBookingTitle: "Book a Pooja",
    poojaBookingDesc: "Select a temple and date for your divine offering.",
    darshanBookingTitle: "Book Darshan",
    darshanBookingDesc: "Schedule your visit for a divine glimpse.",
    selectTier: "Select Tier",
    selectTemple: "Select Temple",
    confirmBooking: "Confirm Booking",
    yatraPackages: "Yatra Packages",
    viewItinerary: "View Itinerary",
    selectPackage: "Select Package",
    numberOfTravellers: "Number of Travellers",
    adults: "Adults",
    selectDepartureDate: "Select Departure Date",
    totalCost: "Total Cost",
    persons: "Persons",
    forgottenTempleTitle: "A Forgotten Temple?",
    forgottenTempleDesc: "Many ancient temples are lost to time. Help us document and preserve our sacred heritage by submitting information about temples you know.",
    uploadTemple: "Submit a Temple",
    addTemple: "Add Temple",
    editTemple: "Edit Temple",
    editUser: "Edit User",
    saveChanges: "Save Changes",
    footerText: "Connecting devotees with the divine, digitally.",
    vrDarshanTitle: "Immersive VR Darshan",
    vrDarshanDesc: "Step into a sacred space from anywhere in the world. Experience a 360-degree virtual reality darshan of ancient temples.",
    experienceNow: "Experience Now",
    aiGuruTitle: "Ask Deva-GPT",
    aiGuruDesc: "Have a question about spirituality, rituals, or a specific temple? Our AI Guru, trained on sacred texts, is here to guide you.",
    aiGuruPlaceholder: "Ask a spiritual question...",
    aiGuruSuggestionsTitle: "Suggestions",
    askGuru: "Ask",
    guruThinking: "Guru is contemplating...",
    login: "Login",
    logout: "Logout",
    signup: "Sign Up",
    loginWithGoogle: "Continue with Google",
    loginWithFacebook: "Continue with Facebook",
    loginOrContinue: "or continue with email",
    welcome: "Welcome",
    templeMap: "Temple on Map",
    backToTemples: "Back to Temples",
    festivalsTitle: "Upcoming Festivals",
    festivalsLoading: "Loading Festivals...",
    festivalsError: "Could not load festival data.",
    gatewayToKnowledge: "Gateway to Knowledge",
    theVedas: "The Four Vedas",
    learnMore: "Learn More",
    readBook: "Read Book",
    addBook: "Add Book",
    editBook: "Edit Book",
    bookNotAvailable: "This book's content is not yet available for reading online.",
    liveDarshanTitle: "Live Darshan",
    liveDarshanButton: "Watch Live",
    nearbyTemplesTitle: "Nearby Temples",
    nearbyTemplesPageTitle: "Nearby Temples",
    loadMore: "Load More",
    showingTemples: "Showing Temples",
    viewAll: "View All",
    exploreAll: "Explore All",
    majorEvents: "Major Events & Festivals",
    addEvent: "Add Event",
    editEvent: "Edit Event",
    bookPandit: "Book Pandit",
    panditBookingTitle: "Book a Pandit",
    panditBookingDesc: "Select an experienced pandit for your ceremony.",
    availablePandits: "Available Pandits",
    availablePoojas: "Available Poojas",
    noPanditsAvailable: "No pandits are currently listed for this event.",
    noPoojasAvailable: "No poojas are currently available for this temple.",
    addPandit: "Add Pandit",
    editPandit: "Edit Pandit",
    delete: "Delete",
    confirmDeleteTitle: "Confirm Deletion",
    confirmDeleteMessage: "Are you sure you want to delete this item? This action cannot be undone.",
    sevaTitle: "Offer Seva",
    sevaDesc: "Your contribution supports temple maintenance, annadanam (food offerings), and various spiritual activities. Be a part of this divine service.",
    donateNow: "Donate Now",
    donateToTemple: "Donate to Temple",
    makeDonation: "Make a Donation",
    donationAmount: "Donation Amount",
    donationPurpose: "Purpose of Donation",
    donationSuccess: "Donation Successful!",
    donationFailed: "Donation Failed.",
    generalDonation: "General Donation",
    foodDonation: "Annadanam (Food Offering)",
    templeMaintenance: "Temple Maintenance",
    gauSeva: "Gau Seva (Cow Protection)",
    vedaPathasala: "Veda Pathasala Support",
    deepaSeva: "Deepa Seva (Sacred Light)",
    locationPermissionDenied: "To use this feature, please enable location services in your browser settings and try again.",
    findingYourLocation: "Finding your location...",
    locationError: "Could not determine your location.",
    away: "away",
    crowdAlertTitle: "High Crowd Alert",
    crowdAlertInfo: "The temple you selected is currently experiencing high crowd levels. For a more peaceful experience, we found a nearby alternative.",
    proceedAnyway: "Proceed Anyway",
    exploreAlternative: "Explore Alternative",
    festivalManagement: "Festival Management",
    addFestival: "Add Festival",
    editFestival: "Edit Festival",
    managePoojas: "Manage Poojas",
    saveAssociations: "Save Associations",
    showPoojaDetails: "Show Pooja Details",
    hidePoojaDetails: "Hide Pooja Details",
    setTask: "Set Task",
    taskFor: "Task for",
    taskDateTime: "Date & Time",
    taskNote: "Note (Optional)",
    taskNotePlaceholder: "e.g., Book travel tickets",
    confirmTask: "Confirm Task",
    myTasks: "My Tasks",
    noTasksSet: "You have no upcoming tasks.",
    deleteTask: "Delete Task",
    notificationPermissionRequest: "To receive notifications, please allow them in your browser.",
    grantPermission: "Grant Permission",
    notificationsBlocked: "Notifications are blocked. Please enable them in your browser settings.",
    manageCategories: "Manage Categories",
    addCategory: "Add Category",
    editCategory: "Edit Category",
    deleteCategory: "Delete Category",
    noCategories: "No categories created yet.",
    categoryName: "Category Name",
    categoryColor: "Category Color",
    confirmDeleteCategoryMessage: "Are you sure you want to delete the category '{categoryName}'? All associated tasks will become uncategorized.",
    uncategorized: "Uncategorized",
    filterAll: "All",

    settingsTitle: "Settings",
    profileSettings: "Profile",
    appearanceSettings: "Appearance",
    languageSettings: "Language & Account",
    accountSettings: "Account",
    deleteAccount: "Delete Account",
    confirmDeleteAccountMessage: "This will permanently delete your account and all associated data. Are you sure?",
    spiritualLevel: "Spiritual Level",
    experiencePoints: "Experience Points",
    xp: "XP",
    dailyStreak: "Daily Streak",
    days: "Days",
    lifetimeStats: "Lifetime Stats",
    templesVisited: "Temples Visited",
    poojasBooked: "Poojas Booked",
    sevaOffered: "Seva Offered",
    knowledgeRead: "Knowledge Read",
    dailySadhana: "Daily Sadhana",
    taskMeditate: "Meditate for 5 minutes",
    taskSeva: "Offer Seva (Donate)",
    taskShloka: "Read daily shloka",
    taskDarshan: "Book a Darshan/Yatra",
    taskChant: "Complete 108 chants (1 Mala)",
    startMeditation: "Start Meditation",
    meditationComplete: "Meditation complete! +50 XP",
    achievements: "Achievements",
    achievementUnlocked: "Achievement Unlocked!",
    achievement_first_step_name: "First Step",
    achievement_first_step_desc: "Completed your first spiritual task.",
    achievement_pilgrim_name: "Pilgrim",
    achievement_pilgrim_desc: "Visited 5 different temples.",
    achievement_devotee_name: "Devotee",
    achievement_devotee_desc: "Booked 5 poojas.",
    achievement_sevak_name: "Sevak",
    achievement_sevak_desc: "Offered seva 3 times.",
    achievement_streak_7_name: "Sadhak",
    achievement_streak_7_desc: "Maintained a 7-day streak.",
    achievement_enlightened_name: "Enlightened",
    achievement_enlightened_desc: "Reached spiritual level 10.",
    pilgrimageOfMonthTitle: "Pilgrimage of the Month",
    pilgrimageOfMonthDesc: "Embark on the sacred Amarnath Yatra, a journey of faith to the ice lingam of Lord Shiva amidst the Himalayas.",
    pilgrimageOfMonthCta: "Explore Yatra Packages",
    feedForYou: "For You, {name}",
    feedDiscover: "Discover",
    reasonVisited: "Because you visited {templeName}",
    reasonPooja: "Because you performed {poojaName}",
    reasonDeity: "A temple for {deityName}",
    reasonPopular: "Popular Choice",
    reasonEvent: "For the upcoming {eventName}",
    navChantingZone: "Chanting Zone",
    chantingZoneTitle: "Chanting Zone",
    chantingZoneForKids: "Kids Chanting Zone",
    chantingZoneSadhanaMode: "Sadhana Mode",
    chantingZoneKidsMode: "Kids Mode",
    chantingZoneSubtitle: "Learn and chant sacred mantras in a fun, interactive way!",
    chantAlongMode: "Chant Along",
    repeatLearnMode: "Repeat & Learn",
    badgeCollection: "Badge Collection",
    chantNow: "Chant Now!",
    chantCountLabel: "Chant Count",
    recordYourVoice: "Record Your Voice",
    stopRecording: "Stop Recording",
    playYourChant: "Play Your Chant",
    recording: "Recording...",
    getReady: "Get Ready...",
    yourTurn: "Your Turn!",
    greatJob: "Great Job!",
    storyMode: "Story Mode",
    bedtimeMantras: "Bedtime Mantras",
    sadhanaModeTitle: "Japa Mala Sadhana",
    sadhanaModeSubtitle: "Complete a round of 108 chants for your daily spiritual practice.",
    japaMalaProgress: "Japa Progress",
    completeMala: "Complete Mala",
    malaCompletedMessage: "Sadhana Complete! +108 XP",
    badge_bhakti_beginner_name: "Bhakti Beginner",
    badge_bhakti_beginner_desc: "Complete 11 chants.",
    badge_chant_champion_name: "Chant Champion",
    badge_chant_champion_desc: "Complete 51 chants.",
    badge_mantra_master_name: "Mantra Master",
    badge_mantra_master_desc: "Complete 108 chants.",
    navChakraSanctuary: "Chakra Sanctuary",
    chakraSanctuaryTitle: "Chakra Sanctuary",
    chakraSahasrara: "Sahasrara",
    chakraSahasraraDesc: "Crown Chakra",
    chakraSahasraraInfo: "The center of spirituality and enlightenment.",
    chakraAjna: "Ajna",
    chakraAjnaDesc: "Third Eye Chakra",
    chakraAjnaInfo: "The center of intuition and foresight.",
    chakraVishuddha: "Vishuddha",
    chakraVishuddhaDesc: "Throat Chakra",
    chakraVishuddhaInfo: "The center of communication and expression.",
    chakraAnahata: "Anahata",
    chakraAnahataDesc: "Heart Chakra",
    chakraAnahataInfo: "The center of love, compassion, and joy.",
    chakraManipura: "Manipura",
    chakraManipuraDesc: "Solar Plexus Chakra",
    chakraManipuraInfo: "The center of self-esteem and personal power.",
    chakraSwadhisthana: "Swadhisthana",
    chakraSwadhisthanaDesc: "Sacral Chakra",
    chakraSwadhisthanaInfo: "The center of creativity and emotions.",
    chakraMuladhara: "Muladhara",
    chakraMuladharaDesc: "Root Chakra",
    chakraMuladharaInfo: "The center of grounding and stability.",
    vedasTitle: "The Vedas",
    vedasSubtitle: "The Foundation of Sanatana Dharma",
    rigvedaTitle: "Rigveda",
    rigvedaSubtitle: "Hymns of Praise",
    rigvedaDesc: "The oldest and most important of the Vedas, containing hymns dedicated to various deities.",
    rigvedaKidDesc: "Imagine a giant book of wonderful poems and songs to the gods, like a big 'thank you' note to nature!",
    samavedaTitle: "Samaveda",
    samavedaSubtitle: "Melodies of Knowledge",
    samavedaDesc: "A collection of melodies and chants derived from the Rigveda, meant for liturgical purposes.",
    samavedaKidDesc: "This is like a divine songbook! It takes the beautiful poems from Rigveda and turns them into happy tunes.",
    yajurvedaTitle: "Yajurveda",
    yajurvedaSubtitle: "Rituals and Sacrifices",
    yajurvedaDesc: "A compilation of prose mantras and sacrificial formulas used during religious ceremonies.",
    yajurvedaKidDesc: "This is like a special recipe book for talking to the gods, with all the secret steps for prayers.",
    atharvavedaTitle: "Atharvaveda",
    atharvavedaSubtitle: "Spells and Incantations",
    atharvavedaDesc: "Contains spells, charms, and hymns for healing, protection, and daily life concerns.",
    atharvavedaKidDesc: "This is a book of magical rhymes for everyday life, like spells for feeling brave or making a plant grow tall!",
    keyTopics: "Key Topics",
    rigvedaTopics: "Cosmology, Deities, Hymns",
    samavedaTopics: "Music, Chants, Liturgy",
    yajurvedaTopics: "Yajna, Rituals, Mantras",
    atharvavedaTopics: "Healing, Magic, Daily Life",
    kidFriendlyMode: "Kid-Friendly Mode",
    readNow: "Read Now",
    listenMantra: "Listen",
    explore: "Explore",
    spiritualTriviaTitle: "Spiritual Trivia",
    spiritualTriviaContent: "Did you know? The Vedas are considered 'Apaurusheya', meaning 'not of human agency'—they are believed to be direct divine revelations.",
    knowledgeHubTitle: "Knowledge Hub",
    dailyWisdom: "Daily Wisdom",
    categoryVeda: "Vedas",
    categoryGita: "Bhagavad Gita",
    categoryUpanishad: "Upanishads",
    categoryPurana: "Puranas",
    categoryItihasa: "Itihasa",
    categorySmriti: "Smritis",
    categoryDarsana: "Darshanas",
    categoryAgama: "Agamas",
    categoryOtherSastra: "Other Shastras",
    categoryGuru: "Spiritual Gurus",
    categoryAncientScience: "Ancient India & Modern Science",
    categoryAnimatedVideos: "Animated Wisdom",
    navSatsang: "Satsang",
    satsangTitle: "Community Satsang",
    satsangDesc: "Join circles of truth, engage in meaningful discussions, and share your spiritual journey with fellow devotees.",
    satsang_general_dharma_name: "General Dharma",
    satsang_general_dharma_desc: "Discuss philosophy, ethics, and daily spiritual practices.",
    satsang_yoga_meditation_name: "Yoga & Meditation",
    satsang_yoga_meditation_desc: "Share experiences and techniques for inner peace.",
    satsang_bhakti_sangeet_name: "Bhakti Sangeet",
    satsang_bhakti_sangeet_desc: "Share and listen to devotional songs and kirtans.",
    satsang_scripture_study_name: "Scripture Study",
    satsang_scripture_study_desc: "Deep dive into the Vedas, Gita, and other sacred texts.",
    satsang_gau_seva_name: "Gauv Seva",
    satsang_gau_seva_desc: "Protect and serve the sacred cows, supporting Gorakshashalas.",
    satsang_temple_rebuilding_name: "Temple Rebuilding",
    satsang_temple_rebuilding_desc: "Join hands to restore and revive ancient, forgotten temples.",
    satsangJoinCircle: "Join Circle",
    satsangSendMessage: "Send",
    satsangTypeMessage: "Type your message...",
    satsangCommunityGuidelines: "Community Guidelines",
    satsangGuidelinesContent: "Be respectful and kind. Share with an open heart. This is a safe space for spiritual growth. No proselytizing or hate speech.",
    viewProfile: "View Profile",
    updateProfilePicture: "Profile Picture",
    profileOf: "Profile of",
    // New Slogan \u0026 Eco-Innovation Keys
    appSlogan: "Everything At One Stop",
    ecoInnovationHub: "Eco-Innovation Hub",
    ecoSustainableDharma: "Sustainable Sanatana Dharma",
    ecoFloralExchange: "Floral Exchange",
    ecoPoojaGadi: "Pooja Gadi",
    ecoInnovationPortal: "Innovation Hub",
    ecoFloralWasteTitle: "Floral Waste Exchange Program",
    ecoFloralWasteDesc: "Don't let your sacred offerings pollute our rivers. Convert them into high-grade organic fertilizers and join the circular path of Dharma.",
    ecoPureCompost: "Pure Microbial Compost",
    ecoChemicalFreeIncense: "Chemical-free Incense",
    ecoWaterPreservation: "Water Body Preservation",
    ecoInputWeightKg: "Input Weight (kg)",
    ecoOrganicReturn: "Organic Product Return",
    ecoSchedulePickup: "SCHEDULE DOORSTEP PICKUP",
    ecoPoojaGadiTitle: "Pooja Gadi Construction",
    ecoPoojaGadiDesc: "Infuse your home altar with the energy of a thousand rituals. These bricks are pressed from Sacred Yagna Bhasma specifically for your sacred space.",
    ecoBrickQuantity: "Brick Quantity",
    ecoCraftsmanshipLevel: "Craftsmanship Level",
    ecoStandard: "Standard",
    ecoSkilledVedic: "Skilled (Vedic)",
    ecoTotalEstimate: "Total Construction Estimate",
    ecoLegalAgreement: "Legal Agreement",
    ecoStrictCompliance: "STRICT COMPLIANCE MANDATE",
    ecoLegalBody: "By procurement of these Sacred Yagna Bhasma Bricks, the User acknowledges and agrees that these units are EXCLUSIVELY for the purpose of constructing Pooja Rooms (Gadis) or Temple Altars. Commercial resale, domestic non-sacred use, or structural repurposing is a violation of Company Policy and subject to immediate legal action under the Law of Company (Dharma Setu Corp).",
    ecoLegalPledge: "I solemnly swear that these materials stay within the Pooja Room.",
    ecoConfirmBook: "CONFIRM \u0026 BOOK BUILD",
    ecoPortalTitle: "Innovation Portal",
    ecoPortalDesc: "Have a ground-breaking idea for eco-friendly Dharma? Pitch your innovation to our engineering team and see it integrated into the Dharma Setu network.",
    ecoInnovationName: "Innovation Name",
    ecoCoreVision: "The Core Vision",
    ecoSubmitReview: "SUBMIT FOR REVIEW",
    ecoVedicInnovations: "Vedic Innovations",
};

const I18N_HI: I18nContent = {
    ...I18N_EN,
    navHome: "होम",
    navTemples: "मंदिर",
    navDarshan: "दर्शन",
    navPoojaServices: "पूजा सेवाएं",
    navYatras: "यात्राएं",
    navKnowledge: "ज्ञान",
    navEvents: "आयोजन",
    navDashboard: "डैशबोर्ड",
    navSeva: "सेवा (दान)",
    navMart: "धर्म मार्ट",
    navSettings: "सेटिंग्स",
    heroTitle: "धर्म सेतु",
    heroSubtitle: "प्राचीन मंदिरों, पवित्र ज्ञान और आध्यात्मिक अनुभवों का आपका डिजिटल प्रवेश द्वार।",
    heroSearchPlaceholder: "मंदिर, पुस्तकें खोजें...",
    dailySloka: "आज का श्लोक",
    translation: "अनुवाद",
    meaning: "अर्थ",
    listen: "सुनें",
    featuredTemples: "प्रमुख मंदिर",
    readMore: "और पढ़ें",
    explorePoojas: "पूजाएं खोजें",
    bookNow: "अभी बुक करें",
    yatraPackages: "यात्रा पैकेज",
    viewItinerary: "यात्रा कार्यक्रम देखें",
    forgottenTempleTitle: "एक भूला हुआ मंदिर?",
    forgottenTempleDesc: "कई प्राचीन मंदिर समय के साथ खो गए हैं। अपनी जानकारी सबमिट करके हमारी पवित्र विरासत को संरक्षित करने में मदद करें।",
    uploadTemple: "मंदिर सबमिट करें",
    vrDarshanTitle: "मनोरम वीआर दर्शन",
    vrDarshanDesc: "दुनिया में कहीं से भी एक पवित्र स्थान में कदम रखें। प्राचीन मंदिरों का 360-डिग्री आभासी वास्तविकता दर्शन का अनुभव करें।",
    experienceNow: "अभी अनुभव करें",
    aiGuruTitle: "देव-जीपीटी से पूछें",
    aiGuruDesc: "क्या आपके पास आध्यात्मिकता, अनुष्ठानों, या किसी विशिष्ट मंदिर के बारे में कोई प्रश्न है? हमारे AI गुरु, पवित्र ग्रंथों पर प्रशिक्षित, आपका मार्गदर्शन करने के लिए यहां हैं।",
    aiGuruPlaceholder: "एक आध्यात्मिक प्रश्न पूछें...",
    festivalsTitle: "आगामी त्यौहार",
    liveDarshanTitle: "लाइव दर्शन",
    liveDarshanButton: "लाइव देखें",
    majorEvents: "प्रमुख आयोजन और त्यौहार",
    sevaTitle: "सेवा प्रदान करें",
    sevaDesc: "Your contribution supports temple maintenance, annadanam (food offerings), and various spiritual activities like Gau Seva. Be a part of this divine service.",
    donateNow: "अभी दान करें",
    knowledgeHubTitle: "ज्ञान केंद्र",
    categoryGuru: "आध्यात्मिक गुरु",
    categoryAncientScience: "प्राचीन भारत और आधुनिक विज्ञान",
    categoryAnimatedVideos: "एनिमेटेड ज्ञान",
    navChantingZone: "मंत्र जाप क्षेत्र",
    chantingZoneTitle: "मंत्र जाप क्षेत्र",
    chantingZoneForKids: "बच्चों का मंत्र जाप क्षेत्र",
    chantingZoneSubtitle: "एक मजेदार, इंटरैक्टिव तरीके से पवित्र मंत्र सीखें और जपें!",
    chantNow: "अभी जाप करें!",
    navChakraSanctuary: "चक्र अभयारण्य",
    chakraSanctuaryTitle: "चक्र अभयारण्य",
    navSatsang: "सत्संग",
    satsangTitle: "सामुदायिक सत्संग",
    satsangDesc: "सत्य के मंडलों में शामिल हों, सार्थक चर्चाओं में संलग्न हों, और साथी भक्तों के साथ अपनी आध्यात्मिक यात्रा साझा करें।",
    satsangJoinCircle: "मंडल में शामिल हों",
    satsangSendMessage: "भेजें",
    satsangTypeMessage: "अपना संदेश लिखें...",
    satsang_general_dharma_name: "सामान्य धर्म",
    satsang_general_dharma_desc: "दर्शन, नैतिकता और दैनिक आध्यात्मिक प्रथाओं पर चर्चा करें।",
    satsang_yoga_meditation_name: "योग और ध्यान",
    satsang_yoga_meditation_desc: "आंतरिक शांति के लिए अनुभव और तकनीकें साझा करें।",
    satsang_bhakti_sangeet_name: "भक्ति संगीत",
    satsang_bhakti_sangeet_desc: "भक्ति गीत और कीर्तन साझा करें और सुनें।",
    satsang_scripture_study_name: "शास्त्र अध्ययन",
    satsang_scripture_study_desc: "वेद, गीता और अन्य पवित्र ग्रंथों में गहरा गोता लगाएँ।",
    satsang_gau_seva_name: "गौ सेवा",
    satsang_gau_seva_desc: "पवित्र गायों की रक्षा और सेवा करें, गौशालाओं का समर्थन करें।",
    satsang_temple_rebuilding_name: "मंदिर पुनर्निर्माण",
    satsang_temple_rebuilding_desc: "प्राचीन, भूले हुए मंदिरों को बहाल करने और पुनर्जीवित करने के लिए हाथ मिलाएं।",
    gauSeva: "गौ सेवा (गौ रक्षा)",
    vedaPathasala: "वेद पाठशाला सहायता",
    deepaSeva: "दीप सेवा (पवित्र ज्योति)",
    setTask: "कार्य सेट करें",
    taskFor: "के लिए कार्य",
    taskDateTime: "दिनांक और समय",
    taskNote: "नोट (वैकल्पिक)",
    taskNotePlaceholder: "जैसे, यात्रा टिकट बुक करें",
    confirmTask: "कार्य की पुष्टि करें",
    myTasks: "मेरे कार्य",
    noTasksSet: "आपके पास कोई आगामी कार्य नहीं है।",
    deleteTask: "कार्य हटाएं",
    // New Slogan \u0026 Eco-Innovation Keys
    appSlogan: "सब कुछ एक ही जगह पर",
    ecoInnovationHub: "इको-इनोवेशन हब",
    ecoSustainableDharma: "स्थायी सनातन धर्म",
    ecoFloralExchange: "पुष्प विनिमय",
    ecoPoojaGadi: "पूजा गद्दी",
    ecoInnovationPortal: "नवाचार केंद्र",
    ecoFloralWasteTitle: "पुष्प अपशिष्ट विनिमय कार्यक्रम",
    ecoFloralWasteDesc: "अपने पवित्र चढ़ावे को हमारी नदियों को प्रदूषित न करने दें। उन्हें उच्च श्रेणी के जैविक उर्वरकों में बदलें और धर्म के चक्र पथ में शामिल हों।",
    ecoPureCompost: "शुद्ध सूक्ष्मजीव खाद",
    ecoChemicalFreeIncense: "रसायन मुक्त अगरबत्ती",
    ecoWaterPreservation: "जल निकाय संरक्षण",
    ecoInputWeightKg: "इनपुट वजन (किग्रा)",
    ecoOrganicReturn: "जैविक उत्पाद रिटर्न",
    ecoSchedulePickup: "डोरस्टेप पिकअप शेड्यूल करें",
    ecoPoojaGadiTitle: "पूजा गद्दी निर्माण",
    ecoPoojaGadiDesc: "अपने घर की वेदी को हजारों अनुष्ठानों की ऊर्जा से भर दें। ये ईंटें विशेष रूप से आपके पवित्र स्थान के लिए पवित्र यज्ञ भस्म से दबाई गई हैं।",
    ecoBrickQuantity: "ईंट की मात्रा",
    ecoCraftsmanshipLevel: "शिल्प कौशल स्तर",
    ecoStandard: "मानक",
    ecoSkilledVedic: "कुशल (वैदिक)",
    ecoTotalEstimate: "कुल निर्माण अनुमान",
    ecoLegalAgreement: "कानूनी समझौता",
    ecoStrictCompliance: "सख्त अनुपालन जनादेश",
    ecoLegalBody: "इन पवित्र यज्ञ भस्म ईंटों की खरीद से, उपयोगकर्ता स्वीकार करता है और सहमत होता है कि ये इकाइयां विशेष रूप से पूजा कक्षों (गद्दियों) या मंदिर की वेदिकाओं के निर्माण के उद्देश्य से हैं। व्यावसायिक पुनर्विक्रय, घरेलू गैर-पवित्र उपयोग, या संरचनात्मक पुनरुत्थान कंपनी नीति का उल्लंघन है और कंपनी के कानून (धर्म सेतु कॉर्पोरेशन) के तहत तत्काल कानूनी कार्रवाई के अधीन है।",
    ecoLegalPledge: "मैं शपथ लेता हूँ कि ये सामग्रियाँ पूजा कक्ष के अंदर ही रहेंगी।",
    ecoConfirmBook: "पुष्टि करें और निर्माण बुक करें",
    ecoPortalTitle: "नवाचार पोर्टल",
    ecoPortalDesc: "पर्यावरण के अनुकूल धर्म के लिए एक अभूतपूर्व विचार है? अपनी नवाचार हमारी इंजीनियरिंग टीम को पिच करें और इसे धर्म सेतु नेटवर्क में एकीकृत देखें।",
    ecoInnovationName: "नवाचार का नाम",
    ecoCoreVision: "मुख्य विजन",
    ecoSubmitReview: "समीक्षा के लिए सबमिट करें",
    ecoVedicInnovations: "वैदिक नवाचार",
};

const I18N_TE: I18nContent = {
    ...I18N_EN,
    navHome: "హోమ్",
    navTemples: "దేవాలయాలు",
    navDarshan: "దర్శనం",
    navPoojaServices: "పూజ సేవలు",
    navYatras: "యాత్రలు",
    navKnowledge: "జ్ఞానం",
    navEvents: "కార్యక్రమాలు",
    navDashboard: "డాష్‌బోర్డ్",
    navSeva: "సేవ (విరాళం)",
    navMart: "ధర్మ మార్ట్",
    navSettings: "సెట్టింగ్‌లు",
    heroTitle: "ధర్మ సేతు",
    heroSubtitle: "ప్రాచీన దేవాలయాలు, పవిత్ర జ్ఞానం మరియు ఆధ్యాత్మిక అనుభవాలకు మీ డిజిటల్ గేట్‌వే.",
    heroSearchPlaceholder: "దేవాలయాలు, పుస్తకాల కోసం శోధించండి...",
    dailySloka: "రోజు శ్లోకం",
    translation: "అనువాదం",
    meaning: "అర్థం",
    listen: "వినండి",
    featuredTemples: "ప్రసిద్ధ దేవాలయాలు",
    readMore: "ఇంకా చదవండి",
    explorePoojas: "పూజలను అన్వేషించండి",
    bookNow: "ఇప్పుడే బుక్ చేయండి",
    yatraPackages: "యాత్ర ప్యాకేజీలు",
    viewItinerary: "యాత్ర వివరాలు చూడండి",
    forgottenTempleTitle: "మరచిపోయిన ఆలయం?",
    forgottenTempleDesc: "చాలా పురాతన దేవాలయాలు కాలక్రమేణా కనుమరుగయ్యాయి. మీకు తెలిసిన దేవాలయాల గురించి సమాచారాన్ని సమర్పించడం ద్వారా మా పవిత్ర వారసత్వాన్ని పత్రబద్ధం చేయడానికి మరియు సంరక్షించడానికి సహాయపడండి.",
    uploadTemple: "ఆలయాన్ని సమర్పించండి",
    vrDarshanTitle: "లీనమయ్యే VR దర్శనం",
    vrDarshanDesc: "ప్రపంచంలో ఎక్కడి నుండైనా పవిత్ర స్థలంలోకి అడుగు పెట్టండి. ప్రాచీన దేవాలయాల 360-డిగ్రీల వర్చువల్ రియాలిటీ దర్శనాన్ని అనుభవించండి.",
    experienceNow: "ఇప్పుడే అనుభవించండి",
    aiGuruTitle: "దేవ-జిపిటిని అడగండి",
    aiGuruDesc: "ఆధ్యాత్మికత, ఆచారాలు లేదా ఒక నిర్దిష్ట ఆలయం గురించి మీకు ప్రశ్న ఉందా? పవిత్ర గ్రంథాలపై శిక్షణ పొందిన మా AI గురువు మీకు మార్గనిర్దేశం చేయడానికి ఇక్కడ ఉన్నారు.",
    aiGuruPlaceholder: "ఒక ఆధ్యాత్మిక ప్రశ్న అడగండి...",
    festivalsTitle: "రాబోయే పండుగలు",
    liveDarshanTitle: " ప్రత్యక్ష దర్శనం",
    liveDarshanButton: " ప్రత్యక్షంగా చూడండి",
    majorEvents: "ప్రధాన కార్యక్రమాలు & పండుగలు",
    sevaTitle: "సేవ చేయండి",
    sevaDesc: "మీ సహకారం ఆలయ నిర్వహణ, అన్నదానం (ఆహార సమర్పణలు), మరియు వివిధ ఆధ్యాత్మిక కార్యకలాపాలకు మద్దతు ఇస్తుంది. ఈ దైవిక సేవలో భాగం కండి.",
    donateNow: "ఇప్పుడే విరాళం ఇవ్వండి",
    knowledgeHubTitle: "జ్ఞాన కేంద్రం",
    categoryGuru: "ఆధ్యాత్మిక గురువులు",
    categoryAncientScience: "ప్రాచీన భారతదేశం & ఆధునిక విజ్ఞానం",
    categoryAnimatedVideos: "యానిమేటెడ్ జ్ఞానం",
    navChantingZone: "జప క్షేత్రం",
    chantingZoneTitle: "జప క్షేత్రం",
    chantingZoneForKids: "పిల్లల జప క్షేత్రం",
    chantingZoneSubtitle: "వినోదభరితమైన, ఇంటరాక్టివ్ మార్గంలో పవిత్ర మంత్రాలను నేర్చుకోండి మరియు జపించండి!",
    chantNow: "ఇప్పుడే జపించండి!",
    navChakraSanctuary: "చక్ర అభయారణ్యం",
    chakraSanctuaryTitle: "చక్ర అభయారణ్యం",
    navSatsang: "సత్సంగం",
    satsangTitle: "సామూహిక సత్సంగం",
    satsangDesc: "సత్యం యొక్క వృత్తాలలో చేరండి, అర్థవంతమైన చర్చలలో పాల్గొనండి, మరియు తోటి భక్తులతో మీ ఆధ్యాత్మిక ప్రయాణాన్ని పంచుకోండి.",
    satsangJoinCircle: "వృత్తంలో చేరండి",
    satsangSendMessage: "పంపండి",
    satsangTypeMessage: "మీ సందేశాన్ని టైప్ చేయండి...",
    satsang_general_dharma_name: "సాధారణ ధర్మం",
    satsang_general_dharma_desc: "తత్వశాస్త్రం, నీతి, మరియు రోజువారీ ఆధ్యాత్మిక అభ్యాసాల గురించి చర్చించండి.",
    satsang_yoga_meditation_name: "యోగ & ధ్యానం",
    satsang_yoga_meditation_desc: "అంతర్గత శాంతి కోసం అనుభవాలు మరియు పద్ధతులను పంచుకోండి.",
    satsang_bhakti_sangeet_name: "భక్తి సంగీతం",
    satsang_bhakti_sangeet_desc: "భక్తి గీతాలు మరియు కీర్తనలను పంచుకోండి మరియు వినండి.",
    satsang_scripture_study_name: "గ్రంథ అధ్యయనం",
    satsang_scripture_study_desc: "వేదాలు, గీత మరియు ఇతర పవిత్ర గ్రంథాలలోకి లోతుగా ప్రవేశించండి.",
    satsang_gau_seva_name: "గో సేవ",
    satsang_gau_seva_desc: "పవిత్ర గోవుల రక్షణ మరియు సేవ, గోశాలలకు మద్దతు ఇవ్వండి.",
    satsang_temple_rebuilding_name: "దేవాలయ పునర్నిర్మాణం",
    satsang_temple_rebuilding_desc: "పురాతన, విస్మరించబడిన దేవాలయాలను పునరుద్ధరించడానికి మరియు పునరుజ్జీవింపజేయడానికి చేయి కలపండి.",
    gauSeva: "గో సేవ (గోసంరక్షణ)",
    vedaPathasala: "వేద పాఠశాల మద్దతు",
    deepaSeva: "దీప సేవ (పవిత్ర జ్యోతి)",
    setTask: "టాస్క్ సెట్ చేయండి",
    taskFor: "కోసం టాస్క్",
    taskDateTime: "తేదీ & సమయం",
    taskNote: "గమనిక (ఐచ్ఛికం)",
    taskNotePlaceholder: "ఉదా., ప్రయాణ టిక్కెట్లను బుక్ చేయండి",
    confirmTask: "టాస్క్‌ను నిర్ధారించండి",
    myTasks: "నా టాస్క్‌లు",
    noTasksSet: "మీకు రాబోయే టాస్క్‌లు లేవు.",
    deleteTask: "టాస్క్‌ను తొలగించండి",
    // New Slogan \u0026 Eco-Innovation Keys
    appSlogan: "అన్నీ ఒకే చోట",
    ecoInnovationHub: "ఎకో-ఇన్నోవేషన్ హబ్",
    ecoSustainableDharma: "సుస్థిర సనాతన ధర్మం",
    ecoFloralExchange: "పుష్ప వినిమయం",
    ecoPoojaGadi: "పూజా గది",
    ecoInnovationPortal: "ఆవిష్కరణ కేంద్రం",
    ecoFloralWasteTitle: "పుష్ప వ్యర్థాల వినిమయ కార్యక్రమం",
    ecoFloralWasteDesc: "మీ పవిత్ర సమర్పణలు మన నదులను కలుషితం చేయనివ్వకండి. వాటిని అధిక-నాణ్యత సేంద్రియ ఎరువులుగా మార్చండి మరియు ధర్మం యొక్క చక్రీయ మార్గంలో చేరండి.",
    ecoPureCompost: "శుద్ధ సూక్ష్మజీవుల కంపోస్ట్",
    ecoChemicalFreeIncense: "రసాయన రహిత అగరుబత్తులు",
    ecoWaterPreservation: "జల వనరుల సంరక్షణ",
    ecoInputWeightKg: "ఇన్‌పుట్ బరువు (కేజీ)",
    ecoOrganicReturn: "సేంద్రియ ఉత్పత్తి రిటర్న్",
    ecoSchedulePickup: "డోర్‌స్టెప్ పికప్‌ని షెడ్యూల్ చేయండి",
    ecoPoojaGadiTitle: "పూజా గది నిర్మాణం",
    ecoPoojaGadiDesc: "వేలాది ఆచారాల శక్తితో మీ ఇంటి బలిపీఠాన్ని నింపండి. ఈ ఇటుకలు మీ పవిత్ర స్థలం కోసం ప్రత్యేకంగా పవిత్ర యజ్ఞ భస్మం నుండి తయారు చేయబడ్డాయి.",
    ecoBrickQuantity: "ఇటుకల సంఖ్య",
    ecoCraftsmanshipLevel: "నైపుణ్యం స్థాయి",
    ecoStandard: "సాధారణ",
    ecoSkilledVedic: "నైపుణ్యం కలిగిన (వైదిక)",
    ecoTotalEstimate: "మొత్తం నిర్మాణ అంచనా",
    ecoLegalAgreement: "న్యాయపరమైన ఒప్పందం",
    ecoStrictCompliance: "ఖచ్చితమైన నిబంధనల ఆదేశం",
    ecoLegalBody: "ఈ పవిత్ర యజ్ఞ భస్మ ఇటుకలను కొనుగోలు చేయడం ద్వారా, వినియోగదారు ఇవి పూజా గదులు లేదా ఆలయ బలిపీఠాల నిర్మాణానికి మాత్రమే అని అంగీకరిస్తారు. వాణిజ్య పునఃవిక్రయం, గృహేతర పవిత్రత లేని ఉపయోగం కంపెనీ విధానం ప్రకారం నిషిద్ధం మరియు కంపెనీ చట్టం (ధర్మ సేతు కార్పొరేషన్) కింద తక్షణ చట్టపరమైన చర్యలకు లోబడి ఉంటుంది.",
    ecoLegalPledge: "ఈ పదార్థాలు పూజా గదిలోనే ఉంటాయని నేను ప్రమాణం చేస్తున్నాను.",
    ecoConfirmBook: "ధృవీకరించండి మరియు బుక్ చేయండి",
    ecoPortalTitle: "ఆవిష్కరణ పోర్టల్",
    ecoPortalDesc: "పర్యావరణ అనుకూల ధర్మం కోసం మీ దగ్గర ఏదైనా అద్భుతమైన ఆలోచన ఉందా? మా ఇంజనీరింగ్ బృందానికి తెలియజేయండి మరియు ధర్మ సేతు నెట్‌వర్క్‌లో చేర్చండి.",
    ecoInnovationName: "ఆవిష్కరణ పేరు",
    ecoCoreVision: "ప్రధాన లక్ష్యం",
    ecoSubmitReview: "సమీక్ష కోసం సమర్పించండి",
    ecoVedicInnovations: "వైదిక ఆవిష్కరణలు",
};

export const I18N_DATA: Record<Language, I18nContent> = {
    [Language.EN]: I18N_EN,
    [Language.HI]: I18N_HI,
    [Language.TE]: I18N_TE,
};

export const SLOKA_DATA: Record<Language, Sloka[]> = {
    [Language.EN]: [
        { text: "वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ ।\nनिर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा ॥", translation: "O Lord with a curved trunk and a mighty body, brilliant as a million suns, please make all my endeavors free of obstacles, always.", meaning: "An invocation to Lord Ganesha to remove obstacles before any undertaking." },
        { text: "गुरुर्ब्रह्मा गुरुर्विष्णुर्गुरुर्देवो महेश्वरः ।\nगुरुः साक्षात् परं ब्रह्म तस्मै श्रीगुरवे नमः ॥", translation: "The Guru is Brahma, the Guru is Vishnu, the Guru is Maheshwara. The Guru is the absolute reality. Salutations to that revered Guru.", meaning: "This verse emphasizes the supreme importance of the Guru (teacher) in spiritual life, equating the Guru with the Hindu Trinity and the ultimate reality, Brahman." },
        { text: "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन ।\nमा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि ॥", translation: "You have a right to perform your prescribed duties, but you are not entitled to the fruits of your actions. Never consider yourself to be the cause of the results of your activities, nor be attached to inaction.", meaning: "A central teaching from the Bhagavad Gita, advocating for selfless action (Nishkama Karma) without attachment to the results." }
    ],
    [Language.HI]: [
        { text: "वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ ।\nनिर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा ॥", translation: "हे घुमावदार सूंड और विशाल शरीर वाले भगवान, जो लाखों सूर्यों के समान प्रतिभाशाली हैं, कृपया मेरे सभी प्रयासों को हमेशा बाधाओं से मुक्त करें।", meaning: "किसी भी कार्य से पहले बाधाओं को दूर करने के लिए भगवान गणेश का आह्वान।" },
        { text: "गुरुर्ब्रह्मा गुरुर्विष्णुर्गुरुर्देवो महेश्वरः ।\nगुरुः साक्षात् परं ब्रह्म तस्मै श्रीगुरवे नमः ॥", translation: "गुरु ब्रह्मा हैं, गुरु विष्णु हैं, गुरु देव महेश्वर हैं। गुरु ही साक्षात परब्रह्म हैं, उन श्री गुरु को नमस्कार।", meaning: "यह श्लोक आध्यात्मिक जीवन में गुरु (शिक्षक) के सर्वोच्च महत्व पर जोर देता है, गुरु को हिंदू त्रिमूर्ति और अंतिम वास्तविकता, ब्रह्म के बराबर मानता है।" },
        { text: "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन ।\nमा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि ॥", translation: "तुम्हें अपने निर्धारित कर्तव्यों का पालन करने का अधिकार है, पर तुम कर्मों के फल के अधिकारी नहीं हो। तुम न तो कभी अपने आपको अपने कर्मों के फलों का कारण मानो, और न ही कर्म न करने में कभी आसक्त होओ।", meaning: "भगवद् गीता से एक केंद्रीय शिक्षण, जो परिणामों से लगाव के बिना निस्वार्थ कार्रवाई (निष्काम कर्म) की वकालत करता है।" }
    ],
    [Language.TE]: [
        { text: "వక్రతుండ మహాకాయ సూర్యకోటి సమప్రభ ।\nనిర్విఘ్నం కురు మే దేవ సర్వకార్యేషు సర్వదా ॥", translation: "వక్రమైన తొండము, గొప్ప శరీరము గలవాడా, కోటి సూర్యుల కాంతితో సమానమైనవాడా, ఓ దేవా, నా పనులన్నింటిలో ఎల్లప్పుడూ ఆటంకాలు లేకుండా చేయి.", meaning: "ఏదైనా పని ప్రారంభించే ముందు ఆటంకాలను తొలగించడానికి వినాయకుడిని ప్రార్థించడం." },
        { text: "గురుర్బ్రహ్మా గురుర్విష్ణుర్గురుర్దేవో మహేశ్వరః ।\nగురుః సాక్షాత్ పరం బ్రహ్మ తస్మై శ్రీగురవే నమః ॥", translation: "గురువే బ్రహ్మ, గురువే విష్ణువు, గురువే మహేశ్వరుడు. గురువే సాక్షాత్తు పరబ్రహ్మ, అటువంటి శ్రీ గురువుకు నమస్కారములు.", meaning: "ఈ శ్లోకం ఆధ్యాత్మిక జీవితంలో గురువు యొక్క అత్యున్నత ప్రాముఖ్యతను నొక్కి చెబుతుంది, గురువును హిందూ త్రిమూర్తులు మరియు అంతిమ వాస్తవికత అయిన బ్రహ్మంతో సమానం చేస్తుంది." },
        { text: "కర్మణ్యేవాధికారస్తే మా ఫలేషు కదాచన ।\nమా కర్మఫలహేతుర్భూర్మా తే సఙ్గోऽస్త్వకర్మణి ॥", translation: "నీకు కర్మలు చేయుటయందే అధికారము కలదు, కానీ కర్మ ఫలములయందు లేదు. నీవు కర్మ ఫలములకు కారణము కారాదు, మరియు కర్మలు చేయకుండా ఉండటంలో ఆసక్తి కలిగి ఉండరాదు.", meaning: "భగవద్గీత నుండి ఒక కేంద్ర బోధన, ఫలితాలపై ఆసక్తి లేకుండా నిస్వార్థ చర్యను (నిష్కామ కర్మ) సమర్థిస్తుంది." }
    ],
};

// === Deity SVG Images — Beautiful inline art, zero network dependency ===
const _deityImg = (id: number, symbol: string, bg1: string, bg2: string, aura: string, label: string, accent: string): string => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 400" width="300" height="400"><defs><radialGradient id="bg${id}" cx="50%" cy="55%" r="65%"><stop offset="0%" stop-color="${bg1}"/><stop offset="100%" stop-color="${bg2}"/></radialGradient><radialGradient id="aura${id}" cx="50%" cy="40%" r="55%"><stop offset="0%" stop-color="${aura}" stop-opacity="0.55"/><stop offset="100%" stop-color="${bg2}" stop-opacity="0"/></radialGradient><filter id="glow${id}"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><rect width="300" height="400" fill="url(#bg${id})"/><ellipse cx="150" cy="160" rx="130" ry="120" fill="url(#aura${id})"/><circle cx="150" cy="160" r="118" fill="none" stroke="${accent}" stroke-width="0.8" stroke-dasharray="6 10" opacity="0.35"/><circle cx="150" cy="160" r="100" fill="none" stroke="${accent}" stroke-width="0.5" opacity="0.25"/><circle cx="150" cy="72" r="6" fill="${accent}" opacity="0.3"/><circle cx="150" cy="248" r="6" fill="${accent}" opacity="0.3"/><circle cx="62" cy="160" r="6" fill="${accent}" opacity="0.3"/><circle cx="238" cy="160" r="6" fill="${accent}" opacity="0.3"/><circle cx="88" cy="88" r="5" fill="${accent}" opacity="0.25"/><circle cx="212" cy="88" r="5" fill="${accent}" opacity="0.25"/><circle cx="88" cy="232" r="5" fill="${accent}" opacity="0.25"/><circle cx="212" cy="232" r="5" fill="${accent}" opacity="0.25"/><circle cx="150" cy="110" r="58" fill="${bg1}" opacity="0.85" stroke="${accent}" stroke-width="1.5" stroke-opacity="0.4"/><circle cx="150" cy="105" r="70" fill="none" stroke="${accent}" stroke-width="2" opacity="0.5" filter="url(#glow${id})"/><circle cx="150" cy="105" r="78" fill="none" stroke="${accent}" stroke-width="0.8" stroke-dasharray="4 6" opacity="0.3"/><text x="150" y="130" font-size="68" text-anchor="middle" dominant-baseline="middle" filter="url(#glow${id})" opacity="0.92">${symbol}</text><path d="M110 175 Q100 200 95 240 Q92 270 100 290 Q150 310 200 290 Q206 268 205 240 Q200 202 190 175 Q170 185 150 185 Q130 185 110 175Z" fill="${bg1}" opacity="0.7" stroke="${accent}" stroke-width="1" stroke-opacity="0.3"/><path d="M105 190 Q80 200 75 230" fill="none" stroke="${accent}" stroke-width="8" stroke-linecap="round" opacity="0.3"/><path d="M195 190 Q220 200 225 230" fill="none" stroke="${accent}" stroke-width="8" stroke-linecap="round" opacity="0.3"/><ellipse cx="150" cy="360" rx="90" ry="18" fill="${accent}" opacity="0.12"/><rect x="0" y="372" width="300" height="28" fill="${bg2}" opacity="0.95"/><line x1="35" y1="375" x2="265" y2="375" stroke="${accent}" stroke-width="0.5" opacity="0.4"/><text x="150" y="391" font-size="13" text-anchor="middle" fill="${accent}" opacity="0.9" font-family="Georgia,serif" letter-spacing="2">${label}</text></svg>`;
    return `data:image/svg+xml,${encodeURIComponent(svg as string)}`;
};

export const CHANTS_DATA: Chant[] = [
    { id: 1, title: 'Krishna Mantra', deity: 'Krishna', category: 'Krishna', mantra: ['Hare Krishna, Hare Krishna', 'Krishna Krishna, Hare Hare', 'Hare Rama, Hare Rama', 'Rama Rama, Hare Hare'], phonetic: [['Ha-re', 'Krish-na,', 'Ha-re', 'Krish-na'], ['Krish-na', 'Krish-na,', 'Ha-re', 'Ha-re'], ['Ha-re', 'Raa-ma,', 'Ha-re', 'Raa-ma'], ['Raa-ma', 'Raa-ma,', 'Ha-re', 'Ha-re']], story: 'The Maha Mantra — a universal prayer to Radha and Krishna. Chanting it purifies the heart and brings one into divine consciousness.', deityImage: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Krishna_with_flute_and_cow_%281890s%29.jpg', sanskrit: 'हरे कृष्ण', difficulty: 'easy' },
    { id: 2, title: 'Shiva Mantra', deity: 'Shiva', category: 'Shiva', mantra: ['Om Namah Shivaya'], phonetic: [['Om', 'Na-mah', 'Shi-vaa-ya']], story: 'The Panchakshara — five sacred syllables representing the five elements. Om Namah Shivaya means "I bow to Shiva, the supreme consciousness."', deityImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Shiva_by_Raja_Ravi_Varma.jpg/800px-Shiva_by_Raja_Ravi_Varma.jpg', sanskrit: 'ॐ नमः शिवाय', difficulty: 'easy' },
    { id: 3, title: 'Ganesha Mantra', deity: 'Ganesha', category: 'Ganesha', mantra: ['Om Gam Ganapataye Namaha'], phonetic: [['Om', 'Gam', 'Ga-na-pa-ta-ye', 'Na-ma-ha']], story: 'An invocation to Lord Ganesha, the remover of obstacles and bestower of wisdom. Chanted at the start of any new venture for blessings.', deityImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Raja_Ravi_Varma_-_Maharashtrian_lady_with_Ganesh.jpg/800px-Raja_Ravi_Varma_-_Maharashtrian_lady_with_Ganesh.jpg', sanskrit: 'ॐ गं गणपतये नमः', difficulty: 'medium' },
    { id: 4, title: 'Gayatri Mantra', deity: 'Gayatri Devi', category: 'Universal', mantra: ['Om Bhur Bhuvah Suvaha', 'Tat Savitur Vareniyam', 'Bhargo Devasya Dhimahi', 'Dhiyo Yo Nah Prachodayat'], phonetic: [['Om', 'Bhur', 'Bhu-vah', 'Su-va-ha'], ['Tat', 'Sa-vi-tur', 'Va-re-ni-yam'], ['Bhar-go', 'De-vas-ya', 'Dhi-ma-hi'], ['Dhi-yo', 'Yo', 'Nah', 'Pra-cho-da-yaat']], story: 'The most sacred Vedic mantra — a prayer to the Sun as the divine light of wisdom. Chanted at dawn and dusk for enlightenment.', deityImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Gayatri.jpg/800px-Gayatri.jpg', sanskrit: 'गायत्री मंत्र', difficulty: 'hard' },
    { id: 5, title: 'Durga Mantra', deity: 'Durga', category: 'Devi', mantra: ['Sarva Mangala Mangalye', 'Shive Sarvartha Sadhike', 'Sharanye Tryambake Gauri', "Narayani Namo'stute"], phonetic: [['Sar-va', 'Man-ga-la', 'Maan-gal-ye'], ['Shi-ve', 'Sar-vaar-tha', 'Saa-dhi-ke'], ['Sha-ran-ye', 'Try-am-ba-ke', 'Gau-ri'], ['Naa-raa-ya-ni', "Na-mo'-stu-te"]], story: 'A prayer to Maa Durga — the warrior goddess who destroys evil and protects devotees with fierce compassion. She is the mother of the universe.', deityImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Durga_mahisasuramardini.jpg/800px-Durga_mahisasuramardini.jpg', sanskrit: 'सर्वमंगलमांगल्ये', difficulty: 'hard' },
    { id: 6, title: 'Rama Mantra', deity: 'Rama', category: 'Vishnu', mantra: ['Shri Ram, Jai Ram, Jai Jai Ram'], phonetic: [['Shri', 'Raam,', 'Jai', 'Raam,', 'Jai', 'Jai', 'Raam']], story: 'Lord Rama — the ideal king, ideal husband, and ideal son. His name is said to be equivalent to reciting 1000 names of Vishnu.', deityImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Rama_by_Raja_Ravi_Varma.jpg/800px-Rama_by_Raja_Ravi_Varma.jpg', sanskrit: 'श्री राम जय राम', difficulty: 'easy' },
    { id: 7, title: 'Hanuman Mantra', deity: 'Hanuman', category: 'Hanuman', mantra: ['Om Hanumate Namaha', 'Jai Hanuman Gyan Gun Sagar'], phonetic: [['Om', 'Ha-nu-ma-te', 'Na-ma-ha'], ['Jai', 'Ha-nu-maan', 'Gyaan', 'Gun', 'Saa-gar']], story: 'Lord Hanuman — the supreme devotee of Rama. A symbol of courage, strength, and selfless service. His name removes fear and grants protection.', deityImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Hanuman_carrying_Sanjeevani_mountain.jpg/800px-Hanuman_carrying_Sanjeevani_mountain.jpg', sanskrit: 'जय हनुमान', difficulty: 'medium' },
    { id: 8, title: 'Saraswati Mantra', deity: 'Saraswati', category: 'Devi', mantra: ['Om Aim Sarasvatyai Namaha'], phonetic: [['Om', 'Aim', 'Sa-ras-va-tyai', 'Na-ma-ha']], story: 'Goddess Saraswati — the divine personification of knowledge, arts, music, and wisdom. Worshipped by students and all seekers of truth.', deityImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Saraswati_by_Raja_Ravi_Varma.jpg/800px-Saraswati_by_Raja_Ravi_Varma.jpg', sanskrit: 'ॐ ऐं सरस्वत्यै नमः', difficulty: 'medium' },
    { id: 9, title: 'Lakshmi Mantra', deity: 'Lakshmi', category: 'Devi', mantra: ['Om Shreem Mahalakshmyai Namaha'], phonetic: [['Om', 'Shreem', 'Ma-ha-laksh-myai', 'Na-ma-ha']], story: 'Goddess Lakshmi — the bestower of wealth, grace, and prosperity in all its forms: material, spiritual, and relational.', deityImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Lakshmi_by_Raja_Ravi_Varma.jpg/800px-Lakshmi_by_Raja_Ravi_Varma.jpg', sanskrit: 'ॐ श्रीं महालक्ष्म्यै नमः', difficulty: 'medium' },
    { id: 10, title: 'Vishnu Mantra', deity: 'Vishnu', category: 'Vishnu', mantra: ['Om Namo Bhagavate Vasudevaya'], phonetic: [['Om', 'Na-mo', 'Bha-ga-va-te', 'Vaa-su-de-vaa-ya']], story: 'The 12-syllable Dvadasakshara Mantra of the preserver of the universe. It represents complete surrender to the all-pervading Lord.', deityImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Vishnu_by_Raja_Ravi_Varma.jpg/800px-Vishnu_by_Raja_Ravi_Varma.jpg', sanskrit: 'ॐ नमो भगवते वासुदेवाय', difficulty: 'medium' },
    { id: 11, title: 'Murugan Mantra', deity: 'Murugan', category: 'Murugan', mantra: ['Om Sharavanabhavaya Namaha', 'Om Shanmukhaya Namaha'], phonetic: [['Om', 'Sha-ra-va-na-bha-va-ya', 'Na-ma-ha'], ['Om', 'Shan-mu-kha-ya', 'Na-ma-ha']], story: 'Lord Murugan — the warrior god of wisdom and war, son of Shiva. He carries the Vel to destroy ignorance and grant divine knowledge.', deityImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Kartikeya_by_Raja_Ravi_Varma.jpg/800px-Kartikeya_by_Raja_Ravi_Varma.jpg', sanskrit: 'ॐ शरवणभवाय नमः', difficulty: 'hard' },
];

export const CHANTING_BADGES_DATA: Badge[] = [
    { id: 'bhakti_beginner', nameKey: 'badge_bhakti_beginner_name', descriptionKey: 'badge_bhakti_beginner_desc', icon: 'diya', chantCount: 11 },
    { id: 'chant_champion', nameKey: 'badge_chant_champion_name', descriptionKey: 'badge_chant_champion_desc', icon: 'bell', chantCount: 51 },
    { id: 'mantra_master', nameKey: 'badge_mantra_master_name', descriptionKey: 'badge_mantra_master_desc', icon: 'lotus', chantCount: 108 },
];

export const TESTIMONIALS_DATA: Testimonial[] = [
    { id: 1, name: 'Devotee', location: 'Mumbai, IN', quote: 'This app has truly transformed my spiritual practice. The daily slokas and temple information are invaluable.', avatarUrl: '' },
    { id: 2, name: 'Devotee', location: 'London, UK', quote: 'Booking a pooja for my family back home has never been easier. A wonderful service for the diaspora.', avatarUrl: '' },
    { id: 3, name: 'Devotee', location: 'New York, USA', quote: 'The live darshan feature is wonderful. It feels like I am right there in the temple.', avatarUrl: '' }
];

export const DARSHAN_TIERS: DarshanTier[] = [
    { name: 'General Darshan', cost: 0, description: 'General queue for all devotees.' },
    { name: 'Special Darshan', cost: 300, description: 'Quicker access to the sanctum.' },
    { name: 'VIP Darshan', cost: 1000, description: 'Direct access with special assistance.' }
];

export const DARSHAN_TIME_SLOTS = ["06:00 - 07:00", "07:00 - 08:00", "08:00 - 09:00", "09:00 - 10:00", "17:00 - 18:00", "18:00 - 19:00", "19:00 - 20:00", "20:00 - 21:00"];

export const DONATION_OPTIONS: DonationOption[] = [
    { id: 'general', title: 'generalDonation', description: 'Support the daily operations and upkeep of spiritual activities.' },
    { id: 'food', title: 'foodDonation', description: 'Contribute to Annadanam, the sacred offering of food to devotees and the needy.' },
    { id: 'templeMaintenance', title: 'templeMaintenance', description: 'Help preserve the sanctity and structure of the temple for future generations.' },
    { id: 'gauSeva', title: 'gauSeva', description: 'Protect and serve the sacred cows, supporting Goshalas and Vedic cattle care.' },
    { id: 'vedaPathasala', title: 'vedaPathasala', description: 'Support the education of young priests and the preservation of Vedic oral traditions.' },
    { id: 'deepaSeva', title: 'deepaSeva', description: 'Provide oil and ghee for the eternal lamps that illuminate the sanctum.' }
];

export const BELL_SOUND_URL = "https://actions.google.com/sounds/v1/household/small_bell_ringing.ogg";

export const CHAKRA_DATA: ChakraTheme[] = [
    { id: 7, name: 'Sahasrara', color: '#9333ea', descriptionKey: 'chakraSahasraraDesc', detailedInfoKey: 'chakraSahasraraInfo', className: 'theme-sahasrara' },
    { id: 6, name: 'Ajna', color: '#4f46e5', descriptionKey: 'chakraAjnaDesc', detailedInfoKey: 'chakraAjnaInfo', className: 'theme-ajna' },
    { id: 5, name: 'Vishuddha', color: '#2563eb', descriptionKey: 'chakraVishuddhaDesc', detailedInfoKey: 'chakraVishuddhaInfo', className: 'theme-vishuddha' },
    { id: 4, name: 'Anahata', color: '#22c55e', descriptionKey: 'chakraAnahataDesc', detailedInfoKey: 'chakraAnahataInfo', className: 'theme-anahata' },
    { id: 3, name: 'Manipura', color: '#eab308', descriptionKey: 'chakraManipuraDesc', detailedInfoKey: 'chakraManipuraInfo', className: 'theme-manipura' },
    { id: 2, name: 'Swadhisthana', color: '#f97316', descriptionKey: 'chakraSwadhisthanaDesc', detailedInfoKey: 'chakraSwadhisthanaInfo', className: 'theme-swadhisthana' },
    { id: 1, name: 'Muladhara', color: '#dc2626', descriptionKey: 'chakraMuladharaDesc', detailedInfoKey: 'chakraMuladharaInfo', className: 'theme-muladhara' },
];

export const ACHIEVEMENTS_DATA: Achievement[] = [
    { id: 'first_step', nameKey: 'achievement_first_step_name', descriptionKey: 'achievement_first_step_desc', icon: 'diya', condition: (stats, growth) => stats.templesVisited > 0 || stats.poojasBooked > 0 },
    { id: 'pilgrim', nameKey: 'achievement_pilgrim_name', descriptionKey: 'achievement_pilgrim_desc', icon: 'temple', condition: (stats) => stats.templesVisited >= 5 },
    { id: 'devotee', nameKey: 'achievement_devotee_name', descriptionKey: 'achievement_devotee_desc', icon: 'bell', condition: (stats) => stats.poojasBooked >= 5 },
    { id: 'sevak', nameKey: 'achievement_sevak_name', descriptionKey: 'achievement_sevak_desc', icon: 'heart-hand', condition: (stats) => stats.sevaOffered >= 3 },
    { id: 'streak_7', nameKey: 'achievement_streak_7_name', descriptionKey: 'achievement_streak_7_desc', icon: 'flame', condition: (stats, growth) => growth.streak >= 7 },
    { id: 'enlightened', nameKey: 'achievement_enlightened_name', descriptionKey: 'achievement_enlightened_desc', icon: 'lotus', condition: (stats, growth) => growth.level >= 10 },
];

// Solfeggio healing frequencies (Hz) for each chakra — used by Web Audio API
export const CHAKRA_FREQUENCIES: Record<ChakraName, number> = {
    'Muladhara': 396,
    'Swadhisthana': 417,
    'Manipura': 528,
    'Anahata': 639,
    'Vishuddha': 741,
    'Ajna': 852,
    'Sahasrara': 963,
};

// Authentic Bija (seed) mantras for each chakra
const CHAKRA_MANTRAS: Record<ChakraName, { bija: string; sanskrit: string; chant: string }> = {
    'Muladhara':    { bija: 'LAM',  sanskrit: 'लं',  chant: 'Laaaammmm' },
    'Swadhisthana': { bija: 'VAM',  sanskrit: 'वं',  chant: 'Vaaaammmm' },
    'Manipura':     { bija: 'RAM',  sanskrit: 'रं',  chant: 'Raaaammmm' },
    'Anahata':      { bija: 'YAM',  sanskrit: 'यं',  chant: 'Yaaaammmm' },
    'Vishuddha':    { bija: 'HAM',  sanskrit: 'हं',  chant: 'Haaaammmm' },
    'Ajna':         { bija: 'OM',   sanskrit: 'ॐ',   chant: 'Oooommmmm' },
    'Sahasrara':    { bija: 'AUM',  sanskrit: 'ॐ',   chant: 'Aaaa-Uuuu-Mmmm' },
};

// Rich, devotional voiceover scripts — sweet, bhakti-filled guidance
const CHAKRA_VOICEOVERS: Record<ChakraName, string[]> = {
    'Muladhara': [
        'Om Shanti... Close your eyes and breathe deeply.',
        'Feel the sacred earth beneath you... the loving embrace of Bhumi Devi, Mother Earth herself.',
        'Your Muladhara chakra glows with the warm, divine red light of creation.',
        'This is your root... your eternal connection to the cosmos.',
        'Breathe in... and chant with devotion... Lam... Lam... Lam...',
        'Feel the warmth rising... You are safe. You are grounded. You are held by the divine.',
        'Like the great Banyan tree of Prayagraj, your roots run deep into the eternal Dharma.',
        'With each breath, feel Bhagwan\'s love anchoring you to this sacred moment.',
    ],
    'Swadhisthana': [
        'Om... Let your awareness gently rise... like the sacred waters of Maa Ganga.',
        'The Swadhisthana chakra awakens now... glowing with the divine orange light of sunset at Varanasi.',
        'This is the seat of creation... where Maa Saraswati\'s creative shakti flows through you.',
        'Feel the gentle, flowing energy... like a sacred river washing away all that no longer serves you.',
        'Chant with sweetness... Vam... Vam... Vam...',
        'You are the divine artist... painting your life with the colors of devotion and joy.',
        'Let creativity and compassion flow through every cell of your being.',
        'Jai Maa Saraswati... the goddess of flowing wisdom blesses you.',
    ],
    'Manipura': [
        'Om... Feel the sacred fire rising within you... the divine Agni of transformation.',
        'Your Manipura chakra blazes with golden light... like the sacred Aarti flame at Dashashwamedh Ghat.',
        'This is your center of power... where Surya Dev, the Sun God, resides within you.',
        'Feel the warmth spreading... dissolving all doubt... all fear... all hesitation.',
        'Chant with strength and devotion... Ram... Ram... Ram...',
        'You carry the fire of a thousand suns within your soul.',
        'Like Hanuman ji discovering his infinite power... realize the divine strength already within you.',
        'Om Suryaya Namaha... bow to the divine light that you are.',
    ],
    'Anahata': [
        'Om... Now... breathe into the most sacred space of all... your spiritual heart.',
        'The Anahata chakra opens like a thousand-petaled lotus... glowing with emerald green divine light.',
        'This is where Bhagwan Krishna plays his eternal flute... filling your heart with prema... unconditional love.',
        'Feel your heart expanding... embracing all beings with compassion and tenderness.',
        'Chant with love... Yam... Yam... Yam...',
        'Radha and Krishna\'s divine love echoes in every heartbeat of yours.',
        'Forgive... release... and let the nectar of devotion fill every corner of your heart.',
        'Hare Krishna, Hare Rama... love is the highest truth... and you are love itself.',
    ],
    'Vishuddha': [
        'Om... Your awareness rises to the sacred throat... the gateway of divine expression.',
        'The Vishuddha chakra radiates celestial blue... like the infinite sky above Kailash Parvat.',
        'This is where truth becomes sound... where your voice becomes a prayer to the divine.',
        'Feel the vibration of cosmic sound... Nada Brahma... the universe is sound.',
        'Chant with purity... Ham... Ham... Ham...',
        'Speak your truth with love... let every word be a mantra... every breath a devotion.',
        'Like the sacred Vedas that emerged from Brahma\'s lips... your voice carries divine power.',
        'Om Namah Shivaya... let your truth ring like temple bells at dawn.',
    ],
    'Ajna': [
        'Om... Gently bring your awareness to the space between your brows... the divine third eye.',
        'The Ajna chakra awakens with deep indigo light... the eye of Lord Shiva himself.',
        'This is the seat of intuition... where maya dissolves and divine wisdom reveals itself.',
        'In this sacred stillness... past and future merge into the eternal present.',
        'Chant with deep reverence... Om... Om... Om...',
        'See with the eye that never closes... the eye of pure consciousness.',
        'Mahadev opens his third eye not to destroy... but to illuminate the truth.',
        'Trust your inner vision... the divine guru within you sees all... knows all.',
    ],
    'Sahasrara': [
        'Om... You have arrived at the crown... the thousand-petaled lotus of pure consciousness.',
        'The Sahasrara chakra blooms with violet and white divine light... beyond all colors... beyond all form.',
        'This is moksha... liberation... where Atman merges with Paramatman... the individual soul returns to the Supreme.',
        'There is no separation here... you are the universe... the universe is you.',
        'Rest in the sacred vibration... Aum... Aum... Aum...',
        'Like a drop of water returning to the ocean... you dissolve into infinite bliss.',
        'Sat-Chit-Ananda... Existence, Consciousness, Bliss... this is your true nature.',
        'Aham Brahmasmi... I am the Supreme Reality. Om Shanti, Shanti, Shanti.',
    ],
};

export const CHAKRA_MEDITATION_DATA = CHAKRA_DATA.map(c => ({
    id: c.id,
    name: c.name,
    color: c.color,
    top: `${15 + (7 - c.id) * 10}%`,
    animationClass: `animate-chakra-${c.name.toLowerCase()}`,
    symbol: `/assets/chakras/${c.name.toLowerCase()}.svg`,
    mantra: CHAKRA_MANTRAS[c.name].bija,
    sanskritMantra: CHAKRA_MANTRAS[c.name].sanskrit,
    chantText: CHAKRA_MANTRAS[c.name].chant,
    voiceover: CHAKRA_VOICEOVERS[c.name].join(' '),
    voiceoverLines: CHAKRA_VOICEOVERS[c.name],
    frequency: CHAKRA_FREQUENCIES[c.name],
    themeName: c.name,
}));

export const PLACEHOLDER_IMAGE_URL = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 300' width='400' height='300' fill='%23d1d5db'%3E%3Crect width='100%25' height='100%25' fill='%23e5e7eb'/%3E%3Cpath d='M344 32H56c-4.4 0-8 3.6-8 8v208c0 4.4 3.6 8 8 8h288c4.4 0 8-3.6 8-8V40c0-4.4-3.6-8-8-8zm-60 108c-15.5 0-28 12.5-28 28s12.5 28 28 28 28-12.5 28-28-12.5-28-28-28zm-44-64l-84 112h256l-68-88-44 56-60-72z'/%3E%3C/svg%3E";